name: Generate Pacman
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Galaxy-sc
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=#00ff88&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b86e8,#3771d9
      - name: Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/
          git diff --cached --quiet || git commit -m "Update pacman" && git push
